version: '3.4'

services:
  server:
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8001:8001
    env_file:
      - .env
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    tmpfs:
      - /var/lib/postgresql/data
#     volumes:
#       - postgres_volume:/var/lib/postgresql/data
# volumes:
#   postgres_volume: